server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE

  data:
    mongodb:
      database: HotelDb
      host: localhost
      port: 27017

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka